name: ci-golang
on: 
  pull_request:
    branches: 
      - develop

jobs:
  check-applications:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - run: go test
      - run: go run math.go

      - name: Set up QEMU
        uses: docker/setup-qemu-actions@v1

      - name: Set up Docker buildx
        uses: docker/setup-buildx-actions@v1

      - name: Build and test
        id: docker_build
        uses: docker/build-push-actions@v2
        with:
          push: false
          tags: miltonjesus/fc3.0/app:latest